"""YAML renderer: approved ExperimentDraft → configs/experiments/{name}.yaml.

The renderer is the final, deterministic step of the config synthesis pipeline.
It requires draft.approved == True, then:
  - applies changes to the base config
  - normalizes via the existing normalize_ml_config()
  - validates via the existing validate_ml_config() (belt-and-suspenders)
  - hashes via ml_experiment_hash() for provenance
  - writes YAML to configs/experiments/

The LLM is never involved here.  No quant engine code is called.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from src.experiments.config_io import load_config
from src.experiments.ml_config import (
    build_ml_experiment_spec,
    ml_experiment_hash,
    normalize_ml_config,
    validate_ml_config,
)
from src.orchestration.config_generation.draft_schema import (
    ExperimentDraft,
    apply_changes,
)
from src.orchestration.utils.filesystem import experiment_config_path

_YAML_HEADER = """\
# Generated by Quant Research Platform — Config Synthesis
# Base experiment:        {base_experiment}
# Draft hash:             {draft_hash}
# Source proposal hash:   {source_proposal_hash}
#
# Review and run with:
#   python scripts/run_from_config.py configs/experiments/{proposed_name}.yaml

"""


def render_to_yaml(
    draft: ExperimentDraft,
    configs_base: Path | str | None = None,
    base: Path | str | None = None,
    dry_run: bool = False,
) -> str:
    """Render an approved ExperimentDraft to a YAML configuration file.

    Args:
        draft:        An approved ExperimentDraft (approved=True required).
        configs_base: Override for configs/experiments/.
        base:         Not used in rendering; kept for API symmetry.
        dry_run:      If True, returns the YAML string without writing to disk.

    Returns:
        YAML string (always).  Also writes to disk unless dry_run=True.

    Raises:
        ValueError: If draft.approved is False.
        FileNotFoundError: If the base config YAML cannot be found.
        ValueError: If the merged config fails final validation.
    """
    if not draft.approved:
        raise ValueError(
            f"Draft {draft.draft_id!r} has not been approved. "
            "Call approve_draft() before rendering to YAML."
        )

    # Load base config
    config_path = experiment_config_path(draft.base_experiment, configs_base)
    base_config = load_config(config_path)

    # Apply changes, set new name
    merged = apply_changes(base_config, draft.changes)
    merged["name"] = draft.proposed_name

    # Normalize — fills all defaults, consistent with the quant engine
    normalized = normalize_ml_config(merged)

    # Final validation — belt-and-suspenders; validate_ml_config is authoritative
    validate_ml_config(normalized)

    # Compute experiment hash for provenance BEFORE adding metadata block
    spec = build_ml_experiment_spec(normalized)
    exp_hash = ml_experiment_hash(spec)

    # Embed provenance — metadata key is ignored by validate_ml_config
    normalized["metadata"] = {
        "draft_hash": draft.draft_hash,
        "base_experiment": draft.base_experiment,
        "source_proposal_hash": draft.source_proposal_hash,
        "experiment_hash": exp_hash,
    }

    # Build YAML string with provenance header
    yaml_body = yaml.dump(
        normalized,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )
    header = _YAML_HEADER.format(
        base_experiment=draft.base_experiment,
        draft_hash=draft.draft_hash,
        source_proposal_hash=draft.source_proposal_hash,
        proposed_name=draft.proposed_name,
    )
    yaml_str = header + yaml_body

    if not dry_run:
        output_path = experiment_config_path(draft.proposed_name, configs_base)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(yaml_str, encoding="utf-8")

    return yaml_str


