"""Environment-aware rendering profile infrastructure.

Provides a centralised ``get_render_profile`` / ``apply_render_profile`` API
that the canonical export pipeline uses to switch between two environments:

    "report"   — compact institutional publication density (PDF / Markdown)
    "frontend" — browser-inspectable institutional figures:
                 larger typography, stronger lines, higher DPI, breathing room

All canonical figures continue to be generated by the same backend rendering
engine with the same analytical content.  The profile system controls export
*ergonomics*, not visualisation logic.

Usage (orchestrator level)::

    from src.visualization.styles import apply_research_style
    apply_research_style(profile="frontend")   # sets active profile globally
    # ... call all plotting functions unchanged ...

Usage (query)::

    from src.visualization.render_profiles import get_active_profile
    profile = get_active_profile()   # → "report" or "frontend"

Archetype hints (optional, for targeted layout functions)::

    from src.visualization.render_profiles import get_archetype_hint, ARCHETYPE_TIMELINE
    hint = get_archetype_hint(ARCHETYPE_TIMELINE)
    if hint.get("external_legend"):
        _place_legend_outside(ax, ...)
"""

from __future__ import annotations

from typing import Any

import matplotlib as mpl

# ---------------------------------------------------------------------------
# Archetype constants
# ---------------------------------------------------------------------------

ARCHETYPE_DEFAULT = "default"
ARCHETYPE_HEATMAP = "heatmap"
ARCHETYPE_TIMELINE = "timeline"
ARCHETYPE_STACKED = "stacked_area"
ARCHETYPE_BAR = "bar_chart"
ARCHETYPE_ROLLING = "rolling_diagnostics"
ARCHETYPE_CONTRIBUTION = "contribution"

# ---------------------------------------------------------------------------
# Profile definitions
# ---------------------------------------------------------------------------

# Report profile — report/PDF publication density, uses base _RESEARCH_RC
_REPORT_PROFILE: dict[str, Any] = {
    "rc": {},
    "figsize_scale": 1.0,
    "dpi_save": 200,
    "line_width_scale": 1.0,
    "archetype_overrides": {},
}

# Frontend profile — browser-inspectable institutional quality
# Typography targets from spec: titles 18-22pt, labels 15-18pt, ticks 13-16pt,
# legends 13-15pt.  Layout: +25% canvas, 250 DPI, stronger lines.
_FRONTEND_PROFILE: dict[str, Any] = {
    "rc": {
        "font.size": 13,
        "axes.titlesize": 20,
        "axes.labelsize": 16,
        "xtick.labelsize": 13,
        "ytick.labelsize": 13,
        "legend.fontsize": 13,
        "lines.linewidth": 2.0,
        "lines.markersize": 6.0,
        "grid.linewidth": 0.8,
        "savefig.dpi": 250,
    },
    "figsize_scale": 1.25,
    "dpi_save": 250,
    "line_width_scale": 1.4,
    "archetype_overrides": {
        # Heatmaps: extra canvas for dense label grids
        ARCHETYPE_HEATMAP: {
            "figsize_scale": 1.4,
        },
        # Timelines / multi-line rolling series: legend outside plot area
        ARCHETYPE_TIMELINE: {
            "external_legend": True,
            "legend_ncol_max": 6,
        },
        # Stacked-area allocation charts: single-row legend above plot
        ARCHETYPE_STACKED: {
            "external_legend": True,
            "legend_loc": "upper center",
            "legend_ncol": "auto",
        },
        # Annotated bar charts: extra vertical breathing room
        ARCHETYPE_BAR: {
            "annotation_padding": 0.25,
        },
        # Rolling diagnostics: even stronger lines for time-series legibility
        ARCHETYPE_ROLLING: {
            "line_width_scale": 1.6,
        },
        # Feature contribution maps: slightly more legend spacing
        ARCHETYPE_CONTRIBUTION: {
            "external_legend": True,
            "legend_spacing": 0.05,
        },
    },
}

RENDER_PROFILES: dict[str, dict[str, Any]] = {
    "report": _REPORT_PROFILE,
    "frontend": _FRONTEND_PROFILE,
}

# ---------------------------------------------------------------------------
# Active profile state (module-level; single-process research pipeline)
# ---------------------------------------------------------------------------

_active_profile: str = "report"


def get_active_profile() -> str:
    """Return the name of the currently active render profile."""
    return _active_profile


def set_active_profile(name: str) -> None:
    """Set the active render profile by name.

    Raises ValueError for unrecognised profile names.
    """
    if name not in RENDER_PROFILES:
        raise ValueError(
            f"Unknown render profile: {name!r}. "
            f"Available profiles: {sorted(RENDER_PROFILES)}"
        )
    global _active_profile
    _active_profile = name


# ---------------------------------------------------------------------------
# Profile accessors
# ---------------------------------------------------------------------------


def get_render_profile(name: str | None = None) -> dict[str, Any]:
    """Return the profile dict for *name* (or the active profile if None)."""
    key = name if name is not None else _active_profile
    if key not in RENDER_PROFILES:
        raise ValueError(
            f"Unknown render profile: {key!r}. "
            f"Available profiles: {sorted(RENDER_PROFILES)}"
        )
    return RENDER_PROFILES[key]


def apply_render_profile(profile: str | None = None) -> None:
    """Apply a named render profile by updating matplotlib RC params.

    If *profile* is None, applies the currently active profile.
    Also updates the active profile state.
    """
    name = profile if profile is not None else _active_profile
    set_active_profile(name)
    p = get_render_profile(name)
    if p["rc"]:
        mpl.rcParams.update(p["rc"])


# ---------------------------------------------------------------------------
# Layout helpers — queried by plotting functions that opt in to archetype hints
# ---------------------------------------------------------------------------


def get_figsize_scale(
    profile: str | None = None,
    archetype: str = ARCHETYPE_DEFAULT,
) -> float:
    """Return the figsize multiplier for *profile* + *archetype* combination."""
    p = get_render_profile(profile)
    base = float(p.get("figsize_scale", 1.0))
    overrides = p.get("archetype_overrides", {}).get(archetype, {})
    return float(overrides.get("figsize_scale", base))


def get_dpi_save(profile: str | None = None) -> int:
    """Return the save DPI for the given profile."""
    return int(get_render_profile(profile).get("dpi_save", 200))


def get_line_width_scale(
    profile: str | None = None,
    archetype: str = ARCHETYPE_DEFAULT,
) -> float:
    """Return the line-width multiplier for *profile* + *archetype*."""
    p = get_render_profile(profile)
    base = float(p.get("line_width_scale", 1.0))
    overrides = p.get("archetype_overrides", {}).get(archetype, {})
    return float(overrides.get("line_width_scale", base))


def get_archetype_hint(
    archetype: str,
    profile: str | None = None,
) -> dict[str, Any]:
    """Return archetype-specific layout hints for *profile*.

    Returns an empty dict when no overrides are defined for this archetype,
    so callers can safely use ``.get()`` without guarding.

    Example::

        hint = get_archetype_hint(ARCHETYPE_TIMELINE)
        if hint.get("external_legend"):
            ax.legend(bbox_to_anchor=(1.01, 1), loc="upper left", ...)
    """
    p = get_render_profile(profile)
    return dict(p.get("archetype_overrides", {}).get(archetype, {}))
